when:
  - event: [push,manual]
    branch: main

steps:
    - name: Build and Release
      image: python:3.13
      environment:
        PYPI_USERNAME:
          from_secret: PYPI_USERNAME
        PYPI_PASSWORD:
          from_secret: PYPI_PASSWORD
      commands:
          - pip install build twine
          - python -m build
          - twine upload dist/* -u $PYPI_USERNAME -p $PYPI_PASSWORD