when:
  - event: [push,manual]
    branch: [main,master]

steps:
    - name: Build and Release
      image: python:3.13
      environment:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD:
          from_secret: PYPI_TOKEN
      commands:
          - pip install build twine
          - python -m build
          - twine upload dist/*